### ISSUE TITLE
Errors are not visible

### ISSUE THREAD

**Issue by ilyalesik** [TalentLayer-Labs/indie-frontend#59]
How to reproduce: go to Create your TalentLayer ID step, try to press "create" button with insufficient balance (I reproduced with 1.1 matic) => an error message is only at console

Possible solutions: show toast message with an error

<img width="1680" alt="Screenshot 2023-04-04 at 17 52 54" src="https://user-images.githubusercontent.com/1270648/229814868-4dcaa09a-c0af-42a7-b3da-302148a39666.png">

**Comment by 0xRomain** [comment]
fixed
